#!/bin/sh

DATABASE=budgettest
USER=budgettest

psql --username=$USER $DATABASE << EOF

DROP TABLE IF EXISTS ROLES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS ACCOUNT CASCADE;
DROP TABLE IF EXISTS TRANSACT CASCADE;
DROP TABLE IF EXISTS BALANCE CASCADE;
DROP TABLE IF EXISTS REQUEST CASCADE;

EOF

