#!/bin/sh

DATABASE=budgettest
USER=budgettest
psql --username=$USER $DATABASE << EOF

ALTER TABLE USERS ADD COLUMN HIDE INTEGER;
UPDATE USERS SET HIDE=0;
ALTER TABLE USERS ALTER COLUMN HIDE SET NOT NULL;
ALTER TABLE USERS ADD CONSTRAINT CC1 CHECK(HIDE = 0 OR HIDE = 1);

EOF

